import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

// Register a standard font if needed, but Helvetica is default and safe
// Font.register({ family: 'Inter', src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hjp-Ek-_EeA.woff' });

const styles = StyleSheet.create({
    page: {
        padding: 40,
        fontFamily: 'Helvetica',
        fontSize: 12,
        lineHeight: 1.5,
        color: '#333',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        marginBottom: 8,
        fontWeight: 'bold',
        color: '#111',
    },
    metadata: {
        fontSize: 10,
        color: '#666',
        marginBottom: 4,
    },
    section: {
        marginBottom: 15,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 6,
        color: '#222',
        backgroundColor: '#f5f5f5',
        padding: 4,
    },
    text: {
        marginBottom: 8,
        textAlign: 'justify',
    },
    recommendations: {
        marginTop: 20,
        padding: 10,
        backgroundColor: '#f9f9f9',
        borderRadius: 4,
    },
    recommendationItem: {
        flexDirection: 'row',
        marginBottom: 4,
    },
    bullet: {
        width: 10,
    },
    recText: {
        flex: 1,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        fontSize: 8,
        textAlign: 'center',
        color: '#aaa',
        borderTopWidth: 1,
        borderTopColor: '#eee',
        paddingTop: 10,
    },
});

interface ReportSection {
    title: string;
    content: string;
}

interface ReportData {
    title: string;
    timestamp: string;
    analyst: string;
    template: string;
    summary: string;
    sections: ReportSection[];
    recommendations: string[];
}

interface ReportPDFProps {
    report: ReportData;
}

const ReportPDF: React.FC<ReportPDFProps> = ({ report }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            {/* Header */}
            <View style={styles.header}>
                <Text style={styles.title}>{report.title}</Text>
                <Text style={styles.metadata}>Generated: {new Date(report.timestamp).toLocaleString()}</Text>
                <Text style={styles.metadata}>Analyst ID: {report.analyst}</Text>
                <Text style={styles.metadata}>Template: {report.template}</Text>
            </View>

            {/* Summary */}
            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Executive Summary</Text>
                <Text style={styles.text}>{report.summary}</Text>
            </View>

            {/* Sections */}
            {report.sections.map((section, index) => (
                <View key={index} style={styles.section}>
                    <Text style={styles.sectionTitle}>{section.title}</Text>
                    <Text style={styles.text}>{section.content}</Text>
                </View>
            ))}

            {/* Recommendations */}
            {report.recommendations && report.recommendations.length > 0 && (
                <View style={styles.recommendations}>
                    <Text style={styles.sectionTitle}>Recommendations</Text>
                    {report.recommendations.map((rec, index) => (
                        <View key={index} style={styles.recommendationItem}>
                            <Text style={styles.bullet}>•</Text>
                            <Text style={styles.recText}>{rec}</Text>
                        </View>
                    ))}
                </View>
            )}

            {/* Footer */}
            <View style={styles.footer}>
                <Text>Confidential - Generated by FinGuard AI Analyst Platform</Text>
            </View>
        </Page>
    </Document>
);

export default ReportPDF;
